routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home')->middleware(['verified', 'auth']);

Route::prefix('dashboard')->middleware(['verified', 'auth'])->group(function () {
    Route::resource('company', 'Web\CompanyController');
    Route::post('/company/{company}/invite', 'Web\CompanyController@invite')->name('company.invite');
    Route::post('/company/{company}/detach', 'Web\CompanyController@detach')->name('company.detach');

    Route::resource('client', 'Web\ClientController')->except([
        'store'
    ]);

    Route::post('/company/{company}/client', 'Web\ClientController@store')->name('client.store');

    Route::get('/client/{client}/loan', 'Web\LoanController@index')->name('loan.index');
    Route::get('/client/{client}/loan/create', 'Web\LoanController@create')->name('loan.create');
    Route::post('/client/{client}/loan/create', 'Web\LoanController@store')->name('loan.store');


    Route::get('/client/{client}/loan/{loan}', 'Web\LoanController@termsAndCondition')->name('loan.terms');


    Route::post('/loan/{loan}/payment', 'Web\LoanController@payment')->name('loan.payment');
    Route::patch('/loan/{loan}', 'Web\LoanController@update')->name('loan.update');

});

Auth::routes(['verify' => true]);

resources/views/partials/dashboard-navigation.blade.php
<div class="navigation navbar-light bg-white shadow-sm py-2 position-relative" id="dashboard-nav">
    <ul class="nav navbar-light container px-0">
        <li class="nav-item">
            <a class="nav-link active" href="/dashboard/client">Clients</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
    </ul>
</div>

resources/views/partials/footer.blade.php
        
    </body>
</html>

resources/views/partials/header.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    @yield('script')

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>

resources/views/partials/navigation.blade.php
<nav class="navbar navbar-expand-md primary-bg" id="main-nav">
    <div class="container">
        <a class="navbar-brand text-white" href="{{ url('/') }}">
            {{ config('app.name', 'Laravel') }}
        </a>
        <button class="navbar-toggler text-white" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon text-white"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">

            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                    </li>
                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                    @endif
                @else
                    <li class="nav-item dropdown text-white">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle text-white" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('company.index') }}">
                                Company
                            </a>
                            <a class="dropdown-item" href="{{ route('logout') }}"
                                onclick="event.preventDefault();
                                                document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>